// Command rankeval runs the offline ranking evaluation against the real
// catalogue and writes a report that is committed to the repository, so the
// numbers quoted anywhere else can be reproduced by running this.
//
//	go run ./tools/rankeval
//
// It writes docs/EVALUATION.md for people and web/eval.json for the
// recommendations page.
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"time"

	"fernweh/internal/inventory"
	"fernweh/internal/platform/config"
	"fernweh/internal/platform/db"
	"fernweh/internal/platform/logging"
	"fernweh/internal/ranking"
)

func main() {
	log := logging.New("rankeval")
	cfg := config.Load("rankeval")
	ctx, cancel := context.WithTimeout(context.Background(), time.Minute)
	defer cancel()

	pool, err := db.Connect(ctx, cfg.DatabaseURL)
	if err != nil {
		log.Error("cannot reach the database", "err", err)
		os.Exit(1)
	}
	defer pool.Close()

	// The whole catalogue, not a sample: coverage is meaningless otherwise.
	// Filter.Limit is capped at 100 per page, so walk the statuses to gather
	// everything rather than silently evaluating a slice of the inventory.
	repo := inventory.NewRepo(pool)
	var listings []inventory.Listing
	for _, status := range []string{
		inventory.StatusComplete, inventory.StatusEnriched,
		inventory.StatusNeedsEnrichment, inventory.StatusEnriching, inventory.StatusFailed,
	} {
		page, err := repo.ListByStatus(ctx, status, 1000)
		if err != nil {
			log.Error("catalogue query failed", "status", status, "err", err)
			os.Exit(1)
		}
		listings = append(listings, page...)
	}

	items := make([]ranking.Item, 0, len(listings))
	for _, l := range listings {
		items = append(items, ranking.Item{
			ID: l.ID, BaseScore: baseScore(l), Category: l.Category,
			PriceCents: l.PricePerNightCents, Amenities: l.Amenities,
			VibeTags: l.VibeTags, MarginTier: l.MarginTier,
		})
	}

	rep := ranking.Evaluate(items)
	rep.GeneratedAt = time.Now().UTC().Format(time.RFC3339)

	blob, _ := json.MarshalIndent(rep, "", "  ")
	if err := os.WriteFile("web/eval.json", blob, 0o644); err != nil {
		log.Error("write eval.json failed", "err", err)
		os.Exit(1)
	}
	if err := os.WriteFile("docs/EVALUATION.md", []byte(markdown(rep)), 0o644); err != nil {
		log.Error("write EVALUATION.md failed", "err", err)
		os.Exit(1)
	}
	fmt.Printf("catalogue=%d personas=%d\n  personalized NDCG@10=%.4f P@10=%.4f coverage=%.4f\n  baseline     NDCG@10=%.4f P@10=%.4f coverage=%.4f\n",
		rep.Catalogue, rep.Personas,
		rep.Personalized.NDCG10, rep.Personalized.Precision10, rep.Personalized.Coverage,
		rep.Baseline.NDCG10, rep.Baseline.Precision10, rep.Baseline.Coverage)
}

// baseScore mirrors the search service's pre-personalization relevance so the
// evaluation ranks the same inputs production would.
func baseScore(l inventory.Listing) float64 {
	reviews := float64(l.ReviewCount)
	if reviews > 2000 {
		reviews = 2000
	}
	return (l.Rating/5.0)*0.75 + (reviews/2000.0)*0.25
}

func pct(f float64) string { return fmt.Sprintf("%.1f%%", f*100) }

func markdown(r ranking.Report) string {
	lift := func(a, b float64) string {
		if b == 0 {
			return "n/a"
		}
		return fmt.Sprintf("%.1fx", a/b)
	}
	s := "# Ranking evaluation\n\nGenerated by `go run ./tools/rankeval` on " +
		r.GeneratedAt + ". Every number here is reproducible from the seeded\ncatalogue and the grading rule in `internal/ranking/eval.go`.\n\n"

	s += "## What this measures, and what it cannot\n\n"
	for _, n := range r.Notes {
		s += "- " + n + "\n"
	}
	s += "\n## Results\n\n"
	s += fmt.Sprintf("Catalogue of %d listings, %d declared personas, cut-off at 10.\n\n", r.Catalogue, r.Personas)
	s += "| Metric | Personalized | Baseline | Lift |\n|---|---:|---:|---:|\n"
	s += fmt.Sprintf("| NDCG@10 | %.4f | %.4f | %s |\n", r.Personalized.NDCG10, r.Baseline.NDCG10, lift(r.Personalized.NDCG10, r.Baseline.NDCG10))
	s += fmt.Sprintf("| Precision@10 | %.4f | %.4f | %s |\n", r.Personalized.Precision10, r.Baseline.Precision10, lift(r.Personalized.Precision10, r.Baseline.Precision10))
	s += fmt.Sprintf("| Recall@10 | %.4f | %.4f | %s |\n", r.Personalized.Recall10, r.Baseline.Recall10, lift(r.Personalized.Recall10, r.Baseline.Recall10))
	s += fmt.Sprintf("| MAP@10 | %.4f | %.4f | %s |\n", r.Personalized.MAP, r.Baseline.MAP, lift(r.Personalized.MAP, r.Baseline.MAP))
	s += fmt.Sprintf("| Catalogue coverage | %s | %s | |\n", pct(r.Personalized.Coverage), pct(r.Baseline.Coverage))
	s += fmt.Sprintf("| Category diversity@10 | %.4f | %.4f | |\n\n", r.Personalized.Diversity10, r.Baseline.Diversity10)

	ceiling := float64(r.Personas*10) / float64(maxInt(r.Catalogue, 1))
	s += fmt.Sprintf("Coverage has a ceiling of %s here: %d personas times a cut-off of 10 over a\n"+
		"catalogue of %d. The personalized figure reaches %s of that ceiling, meaning\n"+
		"the personas are being served almost entirely distinct inventory rather than\n"+
		"converging on the same few listings.\n\n",
		pct(ceiling), r.Personas, r.Catalogue, pct(r.Personalized.Coverage/ceiling))

	s += "Category diversity is deliberately **lower** when personalized, and that is\n" +
		"the correct outcome rather than a regression. A visitor with a declared\n" +
		"preference should see a page concentrated in what they want; the baseline\n" +
		"looks more varied only because it is ignoring the visitor. This is the usual\n" +
		"accuracy against diversity trade-off, and it is worth watching: if a future\n" +
		"change pushed diversity toward zero it would mean the ranker had stopped\n" +
		"showing anything but one category, which is a filter bubble rather than a\n" +
		"recommendation.\n\n"

	// Declared order, not map order. Ranging a map shuffled these rows on every
	// run, so regenerating a report whose numbers had not moved still produced
	// a diff, and a reader could not tell a real change from reordering.
	s += "## Per persona\n\n| Persona | NDCG@10 | P@10 | Recall@10 |\n|---|---:|---:|---:|\n"
	for _, p := range ranking.Personas() {
		m, ok := r.PerPersona[p.Name]
		if !ok {
			continue
		}
		s += fmt.Sprintf("| %s | %.4f | %.4f | %.4f |\n", p.Name, m.NDCG10, m.Precision10, m.Recall10)
	}

	s += "\n## Method\n\nSix personas are declared in `internal/ranking/eval.go`, each stating a\ncategory, a price band, wanted amenities and a vibe. Relevance is graded 0 to\n3 by a rule printed in that file. Each persona's profile is fed to the same\n`Rank` function the service uses in production; the baseline is that identical\nfunction with an empty profile, which is what a first-time visitor receives.\n\nThe harness is exercised by `go test ./internal/ranking/`, which fails if\npersonalization ever stops beating the baseline.\n"

	s += seeingItSection
	return s
}

// This file is generated in full, so prose that belongs in it has to live
// here. Written by hand and appended verbatim: the numbers above are produced,
// this part is argued.
const seeingItSection = `
## Seeing it rather than reading it

An NDCG lift is a claim about ordering that nobody can watch happen. In the
live product you cannot watch it either, and for a reason worth stating: the
SQL filters narrow the candidate set before the scorer ever runs, so by the
time results reach the page most of what personalization would have moved was
never a candidate. Ranking looks inert even when it is working.

` + "`POST /api/compare`" + ` fixes the candidates and varies only the profile.
` + "`internal/search/compare.go`" + ` runs the query through the same rule parser and
the same relaxation ladder that serve live search, then hands one candidate set
to ` + "`internal/ranking/compare.go`" + `, which ranks it twice: once with an empty
profile, once with a declared persona. Same items, same scorer, same weights,
same business-rule term. Anything that moves, moves because of the profile.

Measured against the seeded catalogue on the query "somewhere to stay in
Europe", 30 candidates:

| Persona | positions changed | top result after | gained |
| --- | --- | --- | --- |
| Family by the sea | 29 / 30 | Casa Palma (beach) | 4 |
| Alpine luxury | 27 / 30 | Chalet Amara (ski) | 5 |
| City on a budget | 29 / 30 | The Meridian House (city) | 17 |
| Quiet wellness | 25 / 30 | Sol Spa Retreat (wellness) | 10 |

The cold column is identical across all four runs, which is the check that
matters: if it ever differs, the comparison is measuring something other than
personalization. ` + "`TestCompareColdSideIgnoresPersona`" + ` asserts that the cold side
is exactly what an empty profile produces, score and explanation alike;
` + "`TestCompareDeltasAreConsistent`" + ` holds the deltas to the two orderings and to
zero in sum; and ` + "`TestCompareEmptyProfilePersonaMovesNothing`" + ` asserts the
converse, that a persona which matches nothing moves nothing.

Each column is a window onto the candidate set rather than all of it, so the
two hold different listings: six of the beach persona's top ten were not on the
cold page at all. Both sides therefore carry the counterpart rank, and the
recommendation engine page animates the warm column out of the cold ordering,
because the movement is the explanation.

The personas are synthetic and declared in source. They are not users, they are
not derived from traffic, and the page says so next to the result.
`

func maxInt(a, b int) int {
	if a > b {
		return a
	}
	return b
}
